const mongoose = require("mongoose");

const enquirySchema = new mongoose.Schema({
    enqNo: { type: String, unique: true }, // Auto-generated by server
    date: { type: String, required: true }, // YYYY-MM-DD format
    enqBy: { type: String, default: "Admin User" },

    // Customer Details
    enqType: String,
    source: String,
    name: { type: String, required: true },
    mobile: { type: String, required: true },
    altMobile: String,
    address: String,

    // Product Details
    product: { type: String, required: true },
    variant: String,
    color: String,
    cost: { type: Number, required: true }, // This maps to "Lead Value"
    paymentMethod: String,

    status: {
        type: String,
        enum: ["New", "In Progress", "Converted", "Closed"],
        default: "New",
    },

    createdAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model("Enquiry", enquirySchema);
